### ISSUE TITLE
File and Data cleanup

### ISSUE THREAD

**Issue by buddh4** [nadilhassan/newsmodule#3]
We have to get sure all data is removed when for example the module is disabled or space is removed, is there a reason you removed the following lines: 

https://github.com/nadilhassan/newsmodule/blob/master/Module.php#L45

Furthermore you'll have to get sure your files are removed when your news are deleted.

**Comment by nadilhassan** [comment]
Yes, It will be done without those codes, That was for testing purpose
Thanks

**Comment by nadilhassan** [comment]
I have re-check that with database tables, without those commented codes , the contents are removed (from disable function).

**Comment by buddh4** [comment]
But have you also tested if the files and file entries are removed? This should be done in the afterDelete function of your Activerecord.

**Comment by nadilhassan** [comment]
I am sorry, I didn't, How can I delete the files which are associated with news? By getting the news image file guid and search for that guid with file and deleting it?

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-modules-custom-pages/blob/master/modules/template/models/TemplateContentActiveRecord.php#L152
